name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Set up Android SDK
        uses: actions/setup-android@v3
        with:
          sdk-platform: 'platforms;android-29'
      - name: Create Android emulator
        run: avdmanager create avd -n test-emulator -k "system-images;android-29;google_apis;x86" --device "pixel"
      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v3
        with:
          api-level: 29
          arch: x86
          profile: pixel
          timeout: 600000
      - name: Access kakaoApiKey
        run: echo kakaoApiKey=\"$kakaoApiKey\" > ./RunWithMe/local.properties
        env:
          kakaoApiKey: ${{ secrets.KAKAOAPIKEY }}
      - name: Access naverApiKey
        run: echo naverApiKey=\"$naverApiKey\" > ./RunWithMe/local.properties
        env:
          naverApiKey: ${{ secrets.NAVERAPIKEY }}
      - name: Access baseURL
        run: echo baseURL=\"$baseURL\" > ./RunWithMe/local.properties
        env:
          baseURL: ${{ secrets.BASEURL }}
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: Build and run tests
        run: |
          cd RunWithMe
          ./gradlew clean build test
          ./gradlew connectedAndroidTest
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Some tests failed. Please check the test results."
          fi
