name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Access kakaoApiKey
        run: echo kakaoApiKey=\"$kakaoApiKey\" > local.properties
      - name: Access naverApiKey
        run: echo naverApiKey=\"$naverApiKey\" > local.properties
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: Build and run tests
        run: |
          cd RunWithMe
          ./gradlew clean build test
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Some tests failed. Please check the test results."
          fi
