name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Access kakaoApiKey
        run: echo kakaoApiKey=\"$kakaoApiKey\" > ./RunWithMe/local.properties
        env:
          kakaoApiKey: ${{ secrets.KAKAOAPIKEY }}
      - name: Access naverApiKey
        run: echo naverApiKey=\"$naverApiKey\" > ./RunWithMe/local.properties
        env:
          naverApiKey: ${{ secrets.NAVERAPIKEY }}
      - name: Access baseURL
        run: echo baseURL=\"$baseURL\" > ./RunWithMe/local.properties
        env:
          baseURL: ${{ secrets.BASEURL }}
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            cd /Users/runner/work/RunWithMe-AOS/RunWithMe-AOS/RunWithMe
            ./gradlew connectedAndroidTest
            if [ $? -eq 0 ]; then
              echo "All tests passed successfully."
            else
              echo "Some tests failed. Please check the test results."
            fi
