name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Access KAKAOAPIKEY
        run: echo KAKAOAPIKEY=\"$KAKAOAPIKEY\" > ./RunWithMe/local.properties
        env:
          KAKAOAPIKEY: ${{ secrets.KAKAOAPIKEY }}
      - name: Access NAVERAPIKEY
        run: echo NAVERAPIKEY=\"$NAVERAPIKEY\" > ./RunWithMe/local.properties
        env:
          NAVERAPIKEY: ${{ secrets.NAVERAPIKEY }}
      - name: Access BASEURL
        run: echo "BASEURL={{ secrets.BASEURL }}" > ./RunWithMe/local.properties
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: Build and run tests
        run: |
          cd RunWithMe
          ./gradlew clean build test
          ./gradlew pixel2api30DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Some tests failed. Please check the test results."
          fi
