name: Android CI

on:
  push:
    branches:
      - "dev"
      - "feat/challenge_members_records"
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create google-services
        run: |
          echo '${{ secrets.GOOGLE_SERVICES }}' > ./RunWithMe/presentation/google-services.json
      - name: Create local.properties
        run: |
          echo "KAKAOAPIKEY={{ secrets.KAKAOAPIKEY }}" > ./RunWithMe/local.properties
          echo "NAVERAPIKEY={{ secrets.NAVERAPIKEY }}" >> ./RunWithMe/local.properties
          echo "BASEURL={{ secrets.BASEURL }}" >> ./RunWithMe/local.properties
          echo "MAIL_ID={{ secrets.MAIL_ID }}" >> ./RunWithMe/local.properties
          echo "MAIL_PASSWORD={{ secrets.MAIL_PASSWORD }}" >> ./RunWithMe/local.properties
          echo "KEY_ALIAS={{ secrets.KEY_ALIAS }}" >> ./RunWithMe/local.properties
          echo "KEY_PASSWORD={{ secrets.KEY_PASSWORD }}" >> ./RunWithMe/local.properties
          echo "STORE_PASSWORD={{ secrets.STORE_PASSWORD }}" >> ./RunWithMe/local.properties
          echo "STORE_FILE={{ secrets.STORE_FILE }}" >> ./RunWithMe/local.properties
      - name: Restore Release_KeyStore File
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > ./RunWithMe/release_keystore.jks
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: directory path
        run: |
          cd RunWithMe
          cd
      - name: ls
        run: |
          cd RunWithMe
          ls
      - name: check local.properties
        run: |
          cd RunWithMe
          cat local.properties
      - name: Build release # apk 빌드
        run: |
          cd RunWithMe
          ./gradlew assembleRelease --stacktrace
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: ./RunWithMe/build/outputs/apk/release/app-release.apk
