name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-29'
      - name: Access kakaoApiKey
        run: echo kakaoApiKey=\"$kakaoApiKey\" > ./RunWithMe/local.properties
        env:
          kakaoApiKey: ${{ secrets.KAKAOAPIKEY }}
      - name: Access naverApiKey
        run: echo naverApiKey=\"$naverApiKey\" > ./RunWithMe/local.properties
        env:
          naverApiKey: ${{ secrets.NAVERAPIKEY }}
      - name: Access baseURL
        run: echo baseURL=\"$baseURL\" > ./RunWithMe/local.properties
        env:
          baseURL: ${{ secrets.BASEURL }}
      - name: Grant execute permissions for gradlew
        run: chmod +x RunWithMe/gradlew
      - name: Build and run tests
        run: |
          cd RunWithMe
          ./gradlew clean build test
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Some tests failed. Please check the test results."
          fi
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          profile: Nexus 6
          script: |
            ./gradlew connectedAndroidTest
            if [ $? -eq 0 ]; then
              echo "All tests passed successfully."
            else
              echo "Some tests failed. Please check the test results."
            fi
